const poemData = [
    { text: "初", py: "chū", zh: "副词，当初，起初，引出故事的开头。", en: "At first," },
    { text: "，", punc: true },
    { text: "权谓吕蒙", py: "quán wèi lǚ méng", zh: "孙权对吕蒙说。<br><strong>谓</strong>：对……说。", en: "Sun Quan said to Lyu Meng," },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "卿", py: "qīng", zh: "代词，古代君对臣或朋友之间的爱称，相当于“你”。", en: "You" },
    { text: "今", py: "jīn", zh: "现在。", en: "now" },
    // 🎯【排比美化】：当涂掌事
    { 
        text: "当涂掌事", 
        py: "dāng tú zhǎng shì", 
        zh: "<strong>大意</strong>：当权掌管政事。<br><strong>当涂</strong>：当权，掌管权力。<br><strong>掌事</strong>：掌管事务。", 
        en: "are in power and handling important affairs,", 
        exam: true 
    },
    { text: "，", punc: true },
    // 🎯【排比美化】：不可不学
    { 
        text: "不可不学", 
        py: "bù kě bù xué", 
        zh: "<strong>固定句式</strong>：不能不学习。<br><strong>提示</strong>：双重否定，表强烈的肯定语气，强调学习的必要性。", 
        en: "cannot live without learning!", 
        exam: true 
    },
    { text: "！", punc: true },
    { text: "”", punc: true },
    // 🎯【排比美化】：蒙辞以军中多务
    { 
        text: "蒙辞以军中多务", 
        py: "méng cí yǐ jūn zhōng duō wù", 
        zh: "<strong>大意</strong>：吕蒙用军中事务繁多来推托。<br><strong>辞</strong>：推托。<br><strong>以</strong>：用、拿。<br><strong>倒装</strong>：介词短语后置句。", 
        en: "Lyu Meng excused himself by using the many military duties.", 
        exam: true 
    },
    { text: "。", punc: true },
    { text: "权", py: "quán", zh: "孙权。", en: "Sun Quan" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "孤", py: "gū", zh: "代词，古代王侯的自称，相当于“我”。", en: "I" },
    { text: "岂欲", py: "qǐ yù", zh: "副词短语，难道想要。<br><strong>岂</strong>：难道；<strong>欲</strong>：想要。", en: "how could I want" },
    { text: "卿", py: "qīng", zh: "你。", en: "you to" },
    // 🎯【排比美化】：治经为博士
    { 
        text: "治经为博士", 
        py: "zhì jīng wéi bó ...", 
        zh: "<strong>大意</strong>：研究儒家经典而成为学官。<br><strong>治</strong>：研究。<br><strong>经</strong>：儒家经书。<br><strong>博士</strong>：古代掌管经学传授的学官。", 
        en: "study classic books to become an academic scholar", 
        exam: true 
    },
    { text: "邪", py: "yé", zh: "文言句末疑问语气词，通“耶”，相当于“吗”或“呢”。", en: "?", exam: true },
    { text: "！", punc: true },
    { text: "但当涉猎", py: "dàn dāng shè liè", zh: "<strong>大意</strong>：只应当粗略地阅读。<br><strong>但</strong>：只，仅仅。<br><strong>涉猎</strong>：粗略地阅读，不求甚解。", en: "You should only read widely", exam: true },
    { text: "，", punc: true },
    { text: "见往事耳", py: "jiàn wǎng shì ěr", zh: "<strong>大意</strong>：了解历史往事罢了。<br><strong>见</strong>：了解，晓悟。<br><strong>耳</strong>：句末语气词，罢了。", en: "to know historical events only.", exam: true },
    { text: "。", punc: true },
    { text: "卿", py: "qīng", zh: "你。", en: "You" },
    { text: "言", py: "yán", zh: "动词，说。", en: "say you have" },
    { text: "多务", py: "duō wù", zh: "事务繁多。", en: "many duties," },
    { text: "，", punc: true },
    { text: "孰若孤", py: "shú ruò gū", zh: "<strong>固定句式</strong>：谁比得上我呢？<br><strong>孰</strong>：谁，哪一个。<br><strong>若</strong>：比得上。", en: "but who can compare to me?", exam: true },
    { text: "？", punc: true },
    { text: "孤", py: "gū", zh: "我（孙权自称）。", en: "I" },
    { text: "常", py: "cháng", zh: "副词，经常，常常。", en: "always" },
    { text: "读书", py: "dú shū", zh: "动宾短语，阅读书籍。", en: "read books," },
    { text: "，", punc: true },
    { text: "自以为", py: "zì yǐ wéi", zh: "固定词组，自己认为。", en: "and I think myself" },
    { text: "大有所益", py: "dà yǒu suǒ yì", zh: "词组，大有益处、有很大的收获。", en: "have gained a lot from it." },
    { text: "。", punc: true },
    { text: "”", punc: true },
    { text: "蒙", py: "méng", zh: "吕蒙。", en: "Lyu Meng" },
    { text: "乃始就学", py: "nǎi shǐ jiù xué", zh: "短语，于是开始从事学习。<br><strong>乃</strong>：于是，就。<br><strong>就学</strong>：从事学习，去上学。", en: "therefore began his studies." },
    { text: "。", punc: true },
    { text: "及鲁肃过寻阳", py: "jí lǔ sù guò xún yáng", zh: "<strong>大意</strong>：等到鲁肃经过寻阳的时候。<br><strong>及</strong>：等到。<br><strong>过</strong>：经过。", en: "When Lu Su passed by Xunyang,", exam: true },
    { text: "，", punc: true },
    { text: "与蒙论议", py: "yǔ méng lùn yì", zh: "动宾短语，跟吕蒙谈论政事、议论军事。", en: "he discussed affairs with Lyu Meng," },
    { text: "，", punc: true },
    { text: "大惊", py: "dà jīng", zh: "副词修饰动词，非常吃惊，大为惊奇。", en: "was very shocked and" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "卿", py: "qīng", zh: "你。", en: "Your" },
    { text: "今者才略", py: "jīn zhě cái lüè", zh: "<strong>大意</strong>：现在的才干和军事谋略。<br><strong>今者</strong>：现在，如今。<br><strong>才略</strong>：才干和谋略。", en: "current talent and wisdom", exam: true },
    { text: "，", punc: true },
    { text: "非复吴下阿蒙", py: "fēi fù wú xià ā méng", zh: "<strong>成语大意</strong>：不再是当年吴下那个没有学识的阿蒙了。<br><strong>非复</strong>：不再是。<br><strong>吴下阿蒙</strong>：比喻缺少学识和眼界的人。", en: "are no longer the unlearned Ameng of old Wu!", exam: true },
    { text: "！", punc: true },
    { text: "”", punc: true },
    { text: "蒙", py: "méng", zh: "吕蒙。", en: "Lyu Meng" },
    { text: "曰", py: "yuē", zh: "说。", en: "said," },
    { text: "：", punc: true },
    { text: "“", punc: true },
    { text: "士别三日", py: "shì bié sān rì", zh: "<strong>成语大意</strong>：有抱负的男子汉或读书人离别三天。<br><strong>士</strong>：有抱负、有学识的男子汉。", en: "When a man of purpose leaves for three days," },
    { text: "，", punc: true },
    { text: "即更刮目相待", py: "jí gèng guǎ mù xiāng dài", zh: "<strong>成语大意</strong>：就要重新擦亮眼睛来看待。<br><strong>即</strong>：就。<br><strong>更</strong>：重新。<br><strong>刮目</strong>：擦亮眼睛，用新眼光看人。", en: "you should look at him with fresh eyes,", exam: true },
    { text: "，", punc: true },
    // 🎯【精准针对截图修正】：大兄何见事之晚乎
    { 
        text: "大兄何見事之晚乎", 
        py: "dài xiōng hé jiàn shì zhī wǎn hū", 
        zh: "<strong>翻译</strong>：长兄怎么认清事物这么晚呢！<br><strong>何</strong>：怎么，为何。<br><strong>见事</strong>：认清事物、识别形势。<br><strong>乎</strong>：句末语气词，表感叹。<br><strong>语法</strong>：文言倒装反问句式。", 
        en: "my big brother, why did you realize this so late!", 
        exam: true 
    },
    { text: "！", punc: true },
    { text: "”", punc: true },
    { text: "肃遂拜蒙母", py: "sù suì bài méng mǔ", zh: "<strong>大意</strong>：鲁肃于是拜见吕蒙的母亲。<br><strong>遂</strong>：于是，就。<br><strong>拜</strong>：下拜行礼（代表极高的尊崇）。", en: "Lu Su then paid respects to Lyu Meng's mother," },
    { text: "，", punc: true },
    { text: "结友而别", py: "jié yǒu ér bié", zh: "连带词组，与吕蒙结为好友，然后告别离开。", en: "made friends with him, and left." },
    { text: "。", punc: true }
];
